class_name MapArtSet
extends Resource
## The map viewer's replaceable art, per specs/18-map-viewer.md. The committed default
## (assets/placeholder/map/map_art_set.tres) points at placeholder SVGs generated by
## tools/generate_placeholder_art.py. Replace the art by overwriting those files or by
## pointing these fields at your own textures; a field left empty makes MapView draw
## the same shape in code instead.
##
## Node art is drawn light grey and tinted with the owner's colour, so textures should
## be light/greyscale for the tint to read.

const NodeDef = preload("res://content/definitions/node_def.gd")

@export var origin_texture: Texture2D
@export var resource_texture: Texture2D
@export var fort_texture: Texture2D
@export var neutral_texture: Texture2D
@export var waypoint_texture: Texture2D
## Drawn beside a node that is hidden from some faction (designer view only).
@export var hidden_badge: Texture2D

## Owner colours, indexed by the faction's position in MapDef.factions (wrapping).
@export var faction_palette: Array[Color] = [
	Color("#b3761d"),
	Color("#a3372a"),
	Color("#4c6b78"),
	Color("#5a4a80"),
	Color("#4c7a52"),
	Color("#8a5a9c"),
]
## Unowned nodes.
@export var neutral_color: Color = Color("#8c8575")
## Lane paths, one colour per lane (wrapping).
@export var lane_colors: Array[Color] = [Color("#4c6b78"), Color("#7a5a3a"), Color("#4c7a52")]
@export var edge_color: Color = Color("#9a927e")
@export var background_color: Color = Color("#f2ecdf")
@export var grid_color: Color = Color(0.43, 0.4, 0.33, 0.12)
@export var label_color: Color = Color("#211d15")


func texture_for(node_type: int) -> Texture2D:
	match node_type:
		NodeDef.NodeType.ORIGIN:
			return origin_texture
		NodeDef.NodeType.RESOURCE:
			return resource_texture
		NodeDef.NodeType.FORT:
			return fort_texture
		NodeDef.NodeType.NEUTRAL:
			return neutral_texture
		NodeDef.NodeType.WAYPOINT:
			return waypoint_texture
	return null
